### ISSUE TITLE
support other git remotes (e.g. github)

### ISSUE THREAD

**Issue by marcmo** [esrlabs/esr-rim#7]
currently not possible: github ssh path

```
 $ rim sync -u ssh://git@github.com:esrlabs/concurrent.git -r master -c app/concurrent
/home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize': the scheme ssh does not accept registry part: git@github.com:esrlabs (or bad hostname?) (URI::InvalidURIError)
    from /home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:218:in `new'
    from /home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:218:in `parse'
    from /home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/lib/rim/processor.rb:60:in `get_absolute_remote_url'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/lib/rim/command_helper.rb:107:in `get_remote_branch_format'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/lib/rim/command_helper.rb:36:in `create_module_info'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/lib/rim/command/sync.rb:66:in `invoke'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/lib/rim/rim.rb:82:in `<top (required)>'
    from /home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/muellero/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/gems/esr-rim-1.2.1/bin/rim:2:in `<top (required)>'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/bin/rim:23:in `load'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/bin/rim:23:in `<main>'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/bin/ruby_executable_hooks:15:in `eval'
    from /home/muellero/.rvm/gems/ruby-2.1.3@inga/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by marcmo** [comment]
any progress on this? without this it's really not possible to use rim with github projects
